name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: install build dependencies
      run: chmod +x scripts/install_build_deps.sh && sudo ./scripts/install_build_deps.sh
    - name: test
      run: make test
      
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install build dependencies
      run: chmod +x scripts/install_build_deps.sh && sudo ./scripts/install_build_deps.sh
    - name: make
      run: make

